# Config file for metals program

default_retention = 0.97 # Value of coin that a show will pay. Is percentage of melt.

use_permille = false # Uses parts per thousand instead of parts per hundred (percent)

tree_fancy_characters = true

currency_symbol = "$" # displayed before prices

current_year = 2026
minimum_year = 1800 # Smallest value that will be interpreted as a year and not a face value.

date_format = "%m/%d/%y"

bullion_hint = " (Bullion)" # Displayed after bullion denominations

enforce_prices_set = false

# ----- Color related config -----
show_color = true # Toggles all color output
colors_8_bit = true # Toggles 8 bit colors on instead of 3 bit colors
show_metal_colors = true # Toggles colored names of metals

# Colors for names of metals. Does nothing if show_metal_colors is false.
# Each value on left is key used in database.
# Each value on right is a color defined in colors.py
[metals_colors]
ag="silver"
au="bright_yellow"
pd="bronze"
pt="rose"
rh="lime"
other="red"

[types_colors]
country="blue"
denomination="purple"
value="yellow"
purchase="teal"

[tags_colors]
bullion="magenta"

[misc_colors]
gain="green"
loss="red"

[db_config]
host="localhost"
port=3306
user="root"
database="coin_data"
# Uncomment password line below if you want to connect to database without
# having to enter your password each time. Be aware that it will be freely visible
# to other users of the system
#password="your_password"
